remote_theme: jekyll/minima@1e8a445
plugins:
  - jekyll-remote-theme
title: DigitFlow - Документация
description: Инормация о платформе.
minima:
  nav_pages:
    - about.md
  hide_site_feed_link: true  # `false` or `null` by default
  show_excerpts: true
